name: Test
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  test-check:
    name: runner / pyaction (github-check)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]
    steps:
      # Checkout this repo and Python Package Template repo for validation testing.
      - uses: actions/checkout@v2
        with: 
          repository: microsoft/python-package-template
          ref: 'dciborow/pyproject'    
      - uses: actions/checkout@v3
        with:
          path: pyaction

      - uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      # Test the action with no enabled steps.
      - name: NoOps
        uses: ./pyaction

      # Test the action with all enabled steps.
      - name: All Ops
        uses: ./pyaction
        with:
          black: true
          bandit: true
          pylint: true
          pyright: true
          pytest: true
